app_bundle_profile_all:
    path: /all
    defaults: { _controller: AppBundle:Profile:all }
    
app_bundle_profile_show:
    path: /show
    defaults: { _controller: AppBundle:Profile:show }
    
app_bundle_profile_show_friends:
    path: /show/friends
    defaults: { _controller: AppBundle:Profile:showFriends }
    
app_bundle_profile_show_friend:
    path: /show/friend/{id}
    defaults: { _controller: AppBundle:Profile:showFriend }
    
app_bundle_profile_edit:
    path: /edit/{id}
    defaults: { _controller: AppBundle:Profile:edit }
    
app_bundle_profile_delete:
    path: /delete/{id}
    defaults: { _controller: AppBundle:Profile:delete }
    
app_bundle_profile_add:
    path: /add/{id}
    defaults: { _controller: AppBundle:Profile:add }
    