app_bundle_home:
    resource: "@AppBundle/Resources/config/home/routing.yml"
    prefix:   /home
    
app_bundle_profile:
    resource: "@AppBundle/Resources/config/profile/routing.yml"
    prefix:   /profile

app_bundle_other_profile:
    resource: "@AppBundle/Resources/config/otherProfile/routing.yml"
    prefix:   /other_profile